name: BTPSA tests APPLICATION
# This file represents a complete version of the "BTP Setup Automator" integration tests
# All tests are executed in sequence on one BTP account to avoid entitlement limits
# This is why not matrix strategy is used
# The steps of a job must execute in any case, so we use always()

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sap-samples/btp-setup-automator:main
      options: --user root
    env:
      BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
      BTPSA_PARAM_GLOBALACCOUNT: ${{ secrets.BTPSA_PARAM_GLOBALACCOUNT }}
      BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
    steps: 
      - name: 'Entitlement test for APPLICATION abapcp-web-router'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-abapcp-web-router-parameters.json'
      - name: 'Entitlement test for APPLICATION ads-configui'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-ads-configui-parameters.json'
      - name: 'Entitlement test for APPLICATION ai-launchpad'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-ai-launchpad-parameters.json'
      - name: 'Entitlement test for APPLICATION alm-ts'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-alm-ts-parameters.json'
      - name: 'Entitlement test for APPLICATION api-management-apiportal'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-api-management-apiportal-parameters.json'
      - name: 'Entitlement test for APPLICATION api-management-devportal'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-api-management-devportal-parameters.json'
      - name: 'Entitlement test for APPLICATION auditlog-viewer'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-auditlog-viewer-parameters.json'
      - name: 'Entitlement test for APPLICATION automationpilot'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-automationpilot-parameters.json'
      - name: 'Entitlement test for APPLICATION Backend-service'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-Backend-service-parameters.json'
      - name: 'Entitlement test for APPLICATION c4-distributed-order-management-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-c4-distributed-order-management-app-parameters.json'
      - name: 'Entitlement test for APPLICATION cias'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-cias-parameters.json'
      - name: 'Entitlement test for APPLICATION cicd-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-cicd-app-parameters.json'
      - name: 'Entitlement test for APPLICATION data-privacy-integration-application'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-data-privacy-integration-application-parameters.json'
      - name: 'Entitlement test for APPLICATION document-information-extraction-application'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-document-information-extraction-application-parameters.json'
      - name: 'Entitlement test for APPLICATION dqmmicroui'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-dqmmicroui-parameters.json'
      - name: 'Entitlement test for APPLICATION eadesigner'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-eadesigner-parameters.json'
      - name: 'Entitlement test for APPLICATION edge-services'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-edge-services-parameters.json'
      - name: 'Entitlement test for APPLICATION enterprise-messaging-hub'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-enterprise-messaging-hub-parameters.json'
      - name: 'Entitlement test for APPLICATION extension-center'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-extension-center-parameters.json'
      - name: 'Entitlement test for APPLICATION feature-flags-dashboard'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-feature-flags-dashboard-parameters.json'
      - name: 'Entitlement test for APPLICATION ibx-connection-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-ibx-connection-app-parameters.json'
      - name: 'Entitlement test for APPLICATION intelligent-situation-automation-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-intelligent-situation-automation-app-parameters.json'
      - name: 'Entitlement test for APPLICATION iotas'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-iotas-parameters.json'
      - name: 'Entitlement test for APPLICATION IRPA'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-IRPA-parameters.json'
      - name: 'Entitlement test for APPLICATION it-prod'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-it-prod-parameters.json'
      - name: 'Entitlement test for APPLICATION LandscapePortal'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-LandscapePortal-parameters.json'
      - name: 'Entitlement test for APPLICATION market-rates-ux'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-market-rates-ux-parameters.json'
      - name: 'Entitlement test for APPLICATION MDMBusinessPartnerApplication'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-MDMBusinessPartnerApplication-parameters.json'
      - name: 'Entitlement test for APPLICATION mdo-one-mds-master'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-mdo-one-mds-master-parameters.json'
      - name: 'Entitlement test for APPLICATION MDOrchestrationApplication'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-MDOrchestrationApplication-parameters.json'
      - name: 'Entitlement test for APPLICATION ocnselfserviceagent'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-ocnselfserviceagent-parameters.json'
      - name: 'Entitlement test for APPLICATION PersonalDataManagerApp'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-PersonalDataManagerApp-parameters.json'
      - name: 'Entitlement test for APPLICATION PortalApplication'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-PortalApplication-parameters.json'
      - name: 'Entitlement test for APPLICATION print-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-print-app-parameters.json'
      - name: 'Entitlement test for APPLICATION process-automation'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-process-automation-parameters.json'
      - name: 'Entitlement test for APPLICATION responsibility-management-application-beta'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-responsibility-management-application-beta-parameters.json'
      - name: 'Entitlement test for APPLICATION responsibilitymanagement-application'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-responsibilitymanagement-application-parameters.json'
      - name: 'Entitlement test for APPLICATION retention-manager-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-retention-manager-app-parameters.json'
      - name: 'Entitlement test for APPLICATION sap-cai-onboarding'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-sap-cai-onboarding-parameters.json'
      - name: 'Entitlement test for APPLICATION sap-identity-services-onboarding'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-sap-identity-services-onboarding-parameters.json'
      - name: 'Entitlement test for APPLICATION sapappgyver'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-sapappgyver-parameters.json'
      - name: 'Entitlement test for APPLICATION sapappstudio'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-sapappstudio-parameters.json'
      - name: 'Entitlement test for APPLICATION SAPLaunchpad'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-SAPLaunchpad-parameters.json'
      - name: 'Entitlement test for APPLICATION SAPWebAnalytics'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-SAPWebAnalytics-parameters.json'
      - name: 'Entitlement test for APPLICATION SAPWorkZone'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-SAPWorkZone-parameters.json'
      - name: 'Entitlement test for APPLICATION sdm-web'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-sdm-web-parameters.json'
      - name: 'Entitlement test for APPLICATION spatialservices-app'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-spatialservices-app-parameters.json'
      - name: 'Entitlement test for APPLICATION tnt-onboard-dataenrichment-dcp'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-tnt-onboard-dataenrichment-dcp-parameters.json'
      - name: 'Entitlement test for APPLICATION WorkflowManagementSaaS'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-WorkflowManagementSaaS-parameters.json'
      - name: 'Entitlement test for APPLICATION wums-c4re-beta'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/APPLICATION-wums-c4re-beta-parameters.json'