#! /usr/bin/env python3
from libs.python.helperGenerator import BTPUSECASE_GEN

mainDataJsoFile = "https://raw.githubusercontent.com/SAP-samples/btp-setup-automator/main/config/btp-base/entitledServices.json"
#######################################################################################
# Initialize the tool and fetch the BTP service list
#######################################################################################
generator = BTPUSECASE_GEN()
generator.fetchEntitledServiceList(mainDataJsoFile)

#######################################################################################
# Generate github pages for service details
#######################################################################################
generator.createPageServiceDetails()

#######################################################################################
# Generate files for test workflows
#######################################################################################
# regions = generator.entitledServices.get("btpenums").get("regions")
# for region in regions:
#     generator.createBtpServiceTests(region)
generator.createBtpServiceTests("us10")
generator.createBtpServiceTests("eu10")
