#! /usr/bin/env python3
from libs.python.helperServiceManager import getServiceData
from libs.python.helperJson import saveJsonToFile

data = getServiceData()

filename = "results.json"
saveJsonToFile(filename, data)
