name: BTPSA tests APPLICATION
# This file represents a complete version of the "BTP Setup Automator" integration tests
# All tests are executed in sequence on one BTP account to avoid entitlement limits
# This is why not matrix strategy is used
# The steps of a job must execute in any case, so we use always()

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sap-samples/btp-setup-automator:main
      options: --user root
    env:
      BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
      BTPSA_PARAM_GLOBALACCOUNT: ${{ secrets.BTPSA_PARAM_GLOBALACCOUNT }}
      BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
    steps: 
      - name: 'Entitlement test for APPLICATION abapcp-web-router in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-abapcp-web-router-parameters.json'
      - name: 'Entitlement test for APPLICATION ads-configui in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-ads-configui-parameters.json'
      - name: 'Entitlement test for APPLICATION ai-launchpad in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-ai-launchpad-parameters.json'
      - name: 'Entitlement test for APPLICATION alm-ts in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-alm-ts-parameters.json'
      - name: 'Entitlement test for APPLICATION api-management-apiportal in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-api-management-apiportal-parameters.json'
      - name: 'Entitlement test for APPLICATION api-management-devportal in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-api-management-devportal-parameters.json'
      - name: 'Entitlement test for APPLICATION auditlog-viewer in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-auditlog-viewer-parameters.json'
      - name: 'Entitlement test for APPLICATION automationpilot in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-automationpilot-parameters.json'
      - name: 'Entitlement test for APPLICATION Backend-service in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-Backend-service-parameters.json'
      - name: 'Entitlement test for APPLICATION c4-distributed-order-management-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-c4-distributed-order-management-app-parameters.json'
      - name: 'Entitlement test for APPLICATION cias in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-cias-parameters.json'
      - name: 'Entitlement test for APPLICATION cicd-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-cicd-app-parameters.json'
      - name: 'Entitlement test for APPLICATION data-privacy-integration-application in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-data-privacy-integration-application-parameters.json'
      - name: 'Entitlement test for APPLICATION document-information-extraction-application in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-document-information-extraction-application-parameters.json'
      - name: 'Entitlement test for APPLICATION dqmmicroui in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-dqmmicroui-parameters.json'
      - name: 'Entitlement test for APPLICATION eadesigner in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-eadesigner-parameters.json'
      - name: 'Entitlement test for APPLICATION edge-services in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-edge-services-parameters.json'
      - name: 'Entitlement test for APPLICATION enterprise-messaging-hub in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-enterprise-messaging-hub-parameters.json'
      - name: 'Entitlement test for APPLICATION extension-center in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-extension-center-parameters.json'
      - name: 'Entitlement test for APPLICATION feature-flags-dashboard in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-feature-flags-dashboard-parameters.json'
      - name: 'Entitlement test for APPLICATION ibx-connection-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-ibx-connection-app-parameters.json'
      - name: 'Entitlement test for APPLICATION intelligent-situation-automation-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-intelligent-situation-automation-app-parameters.json'
      - name: 'Entitlement test for APPLICATION iotas in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-iotas-parameters.json'
      - name: 'Entitlement test for APPLICATION IRPA in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-IRPA-parameters.json'
      - name: 'Entitlement test for APPLICATION it-prod in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-it-prod-parameters.json'
      - name: 'Entitlement test for APPLICATION LandscapePortal in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-LandscapePortal-parameters.json'
      - name: 'Entitlement test for APPLICATION market-rates-ux in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-market-rates-ux-parameters.json'
      - name: 'Entitlement test for APPLICATION MDMBusinessPartnerApplication in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-MDMBusinessPartnerApplication-parameters.json'
      - name: 'Entitlement test for APPLICATION mdo-one-mds-master in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-mdo-one-mds-master-parameters.json'
      - name: 'Entitlement test for APPLICATION MDOrchestrationApplication in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-MDOrchestrationApplication-parameters.json'
      - name: 'Entitlement test for APPLICATION ocnselfserviceagent in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-ocnselfserviceagent-parameters.json'
      - name: 'Entitlement test for APPLICATION PersonalDataManagerApp in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-PersonalDataManagerApp-parameters.json'
      - name: 'Entitlement test for APPLICATION PortalApplication in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-PortalApplication-parameters.json'
      - name: 'Entitlement test for APPLICATION print-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-print-app-parameters.json'
      - name: 'Entitlement test for APPLICATION process-automation in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-process-automation-parameters.json'
      - name: 'Entitlement test for APPLICATION responsibility-management-application-beta in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-responsibility-management-application-beta-parameters.json'
      - name: 'Entitlement test for APPLICATION responsibilitymanagement-application in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-responsibilitymanagement-application-parameters.json'
      - name: 'Entitlement test for APPLICATION retention-manager-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-retention-manager-app-parameters.json'
      - name: 'Entitlement test for APPLICATION sap-cai-onboarding in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-sap-cai-onboarding-parameters.json'
      - name: 'Entitlement test for APPLICATION sap-identity-services-onboarding in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-sap-identity-services-onboarding-parameters.json'
      - name: 'Entitlement test for APPLICATION sapappgyver in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-sapappgyver-parameters.json'
      - name: 'Entitlement test for APPLICATION sapappstudio in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-sapappstudio-parameters.json'
      - name: 'Entitlement test for APPLICATION SAPLaunchpad in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-SAPLaunchpad-parameters.json'
      - name: 'Entitlement test for APPLICATION SAPWebAnalytics in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-SAPWebAnalytics-parameters.json'
      - name: 'Entitlement test for APPLICATION SAPWorkZone in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-SAPWorkZone-parameters.json'
      - name: 'Entitlement test for APPLICATION sdm-web in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-sdm-web-parameters.json'
      - name: 'Entitlement test for APPLICATION spatialservices-app in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-spatialservices-app-parameters.json'
      - name: 'Entitlement test for APPLICATION tnt-onboard-dataenrichment-dcp in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-tnt-onboard-dataenrichment-dcp-parameters.json'
      - name: 'Entitlement test for APPLICATION WorkflowManagementSaaS in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-WorkflowManagementSaaS-parameters.json'
      - name: 'Entitlement test for APPLICATION wums-c4re-beta in region eu10'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu10/APPLICATION-wums-c4re-beta-parameters.json'