name: BTPSA tests SERVICE
# This file represents a complete version of the "BTP Setup Automator" integration tests
# All tests are executed in sequence on one BTP account to avoid entitlement limits
# This is why not matrix strategy is used
# The steps of a job must execute in any case, so we use always()

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sap-samples/btp-setup-automator:main
      options: --user root
    env:
      BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
      BTPSA_PARAM_GLOBALACCOUNT: ${{ secrets.BTPSA_PARAM_GLOBALACCOUNT }}
      BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
    steps: 
      - name: 'Entitlement test for SERVICE alert-notification in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-alert-notification-parameters.json'
      - name: 'Entitlement test for SERVICE application-logs in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-application-logs-parameters.json'
      - name: 'Entitlement test for SERVICE autoscaler in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-autoscaler-parameters.json'
      - name: 'Entitlement test for SERVICE business-rules in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-business-rules-parameters.json'
      - name: 'Entitlement test for SERVICE cis in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-cis-parameters.json'
      - name: 'Entitlement test for SERVICE connectivity in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-connectivity-parameters.json'
      - name: 'Entitlement test for SERVICE content-agent in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-content-agent-parameters.json'
      - name: 'Entitlement test for SERVICE credstore in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-credstore-parameters.json'
      - name: 'Entitlement test for SERVICE destination in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-destination-parameters.json'
      - name: 'Entitlement test for SERVICE enterprise-messaging in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-enterprise-messaging-parameters.json'
      - name: 'Entitlement test for SERVICE feature-flags in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-feature-flags-parameters.json'
      - name: 'Entitlement test for SERVICE hana in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-hana-parameters.json'
      - name: 'Entitlement test for SERVICE hana-cloud in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-hana-cloud-parameters.json'
      - name: 'Entitlement test for SERVICE html5-apps-repo in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-html5-apps-repo-parameters.json'
      - name: 'Entitlement test for SERVICE INFRA in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-INFRA-parameters.json'
      - name: 'Entitlement test for SERVICE jobscheduler in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-jobscheduler-parameters.json'
      - name: 'Entitlement test for SERVICE malware-scanner in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-malware-scanner-parameters.json'
      - name: 'Entitlement test for SERVICE mobile-services in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-mobile-services-parameters.json'
      - name: 'Entitlement test for SERVICE objectstore in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-objectstore-parameters.json'
      - name: 'Entitlement test for SERVICE one-inbox-service in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-one-inbox-service-parameters.json'
      - name: 'Entitlement test for SERVICE portal in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-portal-parameters.json'
      - name: 'Entitlement test for SERVICE postgresql in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-postgresql-parameters.json'
      - name: 'Entitlement test for SERVICE processvisibility in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-processvisibility-parameters.json'
      - name: 'Entitlement test for SERVICE redis in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-redis-parameters.json'
      - name: 'Entitlement test for SERVICE saas-registry in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-saas-registry-parameters.json'
      - name: 'Entitlement test for SERVICE sap-workzone in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-sap-workzone-parameters.json'
      - name: 'Entitlement test for SERVICE scp-launchpad in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-scp-launchpad-parameters.json'
      - name: 'Entitlement test for SERVICE sdm in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-sdm-parameters.json'
      - name: 'Entitlement test for SERVICE service-manager in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-service-manager-parameters.json'
      - name: 'Entitlement test for SERVICE theming in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-theming-parameters.json'
      - name: 'Entitlement test for SERVICE transport in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-transport-parameters.json'
      - name: 'Entitlement test for SERVICE ui5-flexibility-keyuser in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-ui5-flexibility-keyuser-parameters.json'
      - name: 'Entitlement test for SERVICE workflow in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-workflow-parameters.json'
      - name: 'Entitlement test for SERVICE workflowmanagement in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-workflowmanagement-parameters.json'
      - name: 'Entitlement test for SERVICE xsuaa in region eu30'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/eu30/SERVICE-xsuaa-parameters.json'