name: BTPSA tests SERVICE
# This file represents a complete version of the "BTP Setup Automator" integration tests
# All tests are executed in sequence on one BTP account to avoid entitlement limits
# This is why not matrix strategy is used
# The steps of a job must execute in any case, so we use always()

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sap-samples/btp-setup-automator:main
      options: --user root
    env:
      BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
      BTPSA_PARAM_GLOBALACCOUNT: ${{ secrets.BTPSA_PARAM_GLOBALACCOUNT }}
      BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
    steps: 
      - name: 'Entitlement test for SERVICE ASE_PROVISIONING in region us4'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/us4/SERVICE-ASE_PROVISIONING-parameters.json'
      - name: 'Entitlement test for SERVICE COMPUTE_UNIT in region us4'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/us4/SERVICE-COMPUTE_UNIT-parameters.json'
      - name: 'Entitlement test for SERVICE hana-db in region us4'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/btp-setup-automator-config-generator/main/output/usecases/us4/SERVICE-hana-db-parameters.json'