name: BTPSA tests ENVIRONMENT
# This file represents a complete version of the "BTP Setup Automator" integration tests
# All tests are executed in sequence on one BTP account to avoid entitlement limits
# This is why not matrix strategy is used
# The steps of a job must execute in any case, so we use always()

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sap-samples/btp-setup-automator:main
      options: --user root
    env:
      BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
      BTPSA_PARAM_GLOBALACCOUNT: ${{ secrets.BTPSA_PARAM_GLOBALACCOUNT }}
      BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
    steps: 
      - name: 'Entitlement test for ENVIRONMENT cloudfoundry'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile './output/usecases/ENVIRONMENT-cloudfoundry-usecase.json'
      - name: 'Entitlement test for ENVIRONMENT kymaruntime'
        if: ${{ always() }}
        working-directory: /home/user
        shell: bash
        run: ./btpsa -parameterfile './output/usecases/ENVIRONMENT-kymaruntime-usecase.json'